"""Try to fix many to many

Revision ID: 3eab0eaeff17
Revises: 
Create Date: 2022-05-26 17:31:12.517960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eab0eaeff17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('registered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_name'), 'playlist', ['name'], unique=False)
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mbid', sa.String(length=200), nullable=True),
    sa.Column('release_id', sa.String(length=500), nullable=True),
    sa.Column('cover_url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('artist', sa.String(length=300), nullable=True),
    sa.Column('release', sa.String(length=300), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('lyrics', sa.String(length=1000000), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('capo', sa.String(length=100), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_artist'), 'song', ['artist'], unique=False)
    op.create_index(op.f('ix_song_capo'), 'song', ['capo'], unique=False)
    op.create_index(op.f('ix_song_lyrics'), 'song', ['lyrics'], unique=False)
    op.create_index(op.f('ix_song_mbid'), 'song', ['mbid'], unique=False)
    op.create_index(op.f('ix_song_notes'), 'song', ['notes'], unique=False)
    op.create_index(op.f('ix_song_release'), 'song', ['release'], unique=False)
    op.create_index(op.f('ix_song_release_id'), 'song', ['release_id'], unique=False)
    op.create_index(op.f('ix_song_title'), 'song', ['title'], unique=False)
    op.create_index(op.f('ix_song_year'), 'song', ['year'], unique=False)
    op.create_table('song_playlist_association',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'song_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_playlist_association')
    op.drop_index(op.f('ix_song_year'), table_name='song')
    op.drop_index(op.f('ix_song_title'), table_name='song')
    op.drop_index(op.f('ix_song_release_id'), table_name='song')
    op.drop_index(op.f('ix_song_release'), table_name='song')
    op.drop_index(op.f('ix_song_notes'), table_name='song')
    op.drop_index(op.f('ix_song_mbid'), table_name='song')
    op.drop_index(op.f('ix_song_lyrics'), table_name='song')
    op.drop_index(op.f('ix_song_capo'), table_name='song')
    op.drop_index(op.f('ix_song_artist'), table_name='song')
    op.drop_table('song')
    op.drop_index(op.f('ix_playlist_name'), table_name='playlist')
    op.drop_table('playlist')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
