"""user name

Revision ID: 5187f486c396
Revises: 3eab0eaeff17
Create Date: 2022-05-27 01:38:17.860128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5187f486c396'
down_revision = '3eab0eaeff17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pre_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('sur_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_pre_name'), 'user', ['pre_name'], unique=True)
    op.create_index(op.f('ix_user_sur_name'), 'user', ['sur_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sur_name'), table_name='user')
    op.drop_index(op.f('ix_user_pre_name'), table_name='user')
    op.drop_column('user', 'sur_name')
    op.drop_column('user', 'pre_name')
    # ### end Alembic commands ###
