"""Playlist share

Revision ID: d872b8d07aa9
Revises: cf76c0fcb87b
Create Date: 2022-05-28 17:36:42.947511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd872b8d07aa9'
down_revision = 'cf76c0fcb87b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('share', sa.Boolean(), nullable=True))
    op.add_column('playlist', sa.Column('share_link', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_playlist_share_link'), 'playlist', ['share_link'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_share_link'), table_name='playlist')
    op.drop_column('playlist', 'share_link')
    op.drop_column('playlist', 'share')
    # ### end Alembic commands ###
