"""Add playlists

Revision ID: 1e60067944f7
Revises: c0f80d635848
Create Date: 2022-05-25 15:37:59.200512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e60067944f7'
down_revision = 'c0f80d635848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_name'), 'playlist', ['name'], unique=False)
    op.create_table('song_playlist_association',
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_playlist_association')
    op.drop_index(op.f('ix_playlist_name'), table_name='playlist')
    op.drop_table('playlist')
    # ### end Alembic commands ###
