"""empty message

Revision ID: 35c81f340b3b
Revises: db421b4ca9b7
Create Date: 2024-05-29 01:00:48.981928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c81f340b3b'
down_revision = 'db421b4ca9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_pages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('small_font', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('small_font')
        batch_op.drop_column('num_pages')

    # ### end Alembic commands ###
