"""empty message

Revision ID: 8e7599cc7bca
Revises: a0524a2d7eb7
Create Date: 2024-05-29 00:55:45.043281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7599cc7bca'
down_revision = 'a0524a2d7eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_pages', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_song_pages')
        batch_op.create_index(batch_op.f('ix_song_num_pages'), ['num_pages'], unique=False)
        batch_op.drop_column('pages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pages', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_song_num_pages'))
        batch_op.create_index('ix_song_pages', ['pages'], unique=False)
        batch_op.drop_column('num_pages')

    # ### end Alembic commands ###
