"""empty message

Revision ID: a0524a2d7eb7
Revises: c010a06c6539
Create Date: 2024-05-29 00:50:39.959743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0524a2d7eb7'
down_revision = 'c010a06c6539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('small_font', sa.Boolean(), nullable=True))
        batch_op.drop_index('ix_song_small')
        batch_op.create_index(batch_op.f('ix_song_small_font'), ['small_font'], unique=False)
        batch_op.drop_column('small')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('small', sa.BOOLEAN(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_song_small_font'))
        batch_op.create_index('ix_song_small', ['small'], unique=False)
        batch_op.drop_column('small_font')

    # ### end Alembic commands ###
