"""font size

Revision ID: c010a06c6539
Revises: 9eb35c915681
Create Date: 2024-05-28 22:26:21.362087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c010a06c6539'
down_revision = '9eb35c915681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('small', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_song_small'), ['small'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_small'))
        batch_op.drop_column('small')

    # ### end Alembic commands ###
