"""Add songs

Revision ID: c0f80d635848
Revises: 
Create Date: 2022-05-20 14:38:48.063813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f80d635848'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('registered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mbid', sa.String(length=1000), nullable=True),
    sa.Column('release_id', sa.String(length=1000), nullable=True),
    sa.Column('cover_url', sa.String(length=2000), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('artist', sa.String(length=1000), nullable=True),
    sa.Column('release', sa.String(length=1000), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('lyrics', sa.String(length=1000000), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('capo', sa.String(length=1000), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_artist'), 'song', ['artist'], unique=False)
    op.create_index(op.f('ix_song_capo'), 'song', ['capo'], unique=False)
    op.create_index(op.f('ix_song_lyrics'), 'song', ['lyrics'], unique=False)
    op.create_index(op.f('ix_song_mbid'), 'song', ['mbid'], unique=False)
    op.create_index(op.f('ix_song_notes'), 'song', ['notes'], unique=False)
    op.create_index(op.f('ix_song_release'), 'song', ['release'], unique=False)
    op.create_index(op.f('ix_song_release_id'), 'song', ['release_id'], unique=False)
    op.create_index(op.f('ix_song_title'), 'song', ['title'], unique=False)
    op.create_index(op.f('ix_song_year'), 'song', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_year'), table_name='song')
    op.drop_index(op.f('ix_song_title'), table_name='song')
    op.drop_index(op.f('ix_song_release_id'), table_name='song')
    op.drop_index(op.f('ix_song_release'), table_name='song')
    op.drop_index(op.f('ix_song_notes'), table_name='song')
    op.drop_index(op.f('ix_song_mbid'), table_name='song')
    op.drop_index(op.f('ix_song_lyrics'), table_name='song')
    op.drop_index(op.f('ix_song_capo'), table_name='song')
    op.drop_index(op.f('ix_song_artist'), table_name='song')
    op.drop_table('song')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
