"""user name

Revision ID: cf76c0fcb87b
Revises: 5187f486c396
Create Date: 2022-05-27 01:39:25.548297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf76c0fcb87b'
down_revision = '5187f486c396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('prename', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('surname', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_pre_name', table_name='user')
    op.drop_index('ix_user_sur_name', table_name='user')
    op.create_index(op.f('ix_user_prename'), 'user', ['prename'], unique=True)
    op.create_index(op.f('ix_user_surname'), 'user', ['surname'], unique=True)
    op.drop_column('user', 'pre_name')
    op.drop_column('user', 'sur_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sur_name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('pre_name', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_user_surname'), table_name='user')
    op.drop_index(op.f('ix_user_prename'), table_name='user')
    op.create_index('ix_user_sur_name', 'user', ['sur_name'], unique=False)
    op.create_index('ix_user_pre_name', 'user', ['pre_name'], unique=False)
    op.drop_column('user', 'surname')
    op.drop_column('user', 'prename')
    # ### end Alembic commands ###
