"""empty message

Revision ID: db421b4ca9b7
Revises: 8e7599cc7bca
Create Date: 2024-05-29 01:00:20.651124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db421b4ca9b7'
down_revision = '8e7599cc7bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index('ix_song_num_pages')
        batch_op.drop_index('ix_song_small_font')
        batch_op.drop_column('small_font')
        batch_op.drop_column('num_pages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_pages', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('small_font', sa.BOOLEAN(), nullable=True))
        batch_op.create_index('ix_song_small_font', ['small_font'], unique=False)
        batch_op.create_index('ix_song_num_pages', ['num_pages'], unique=False)

    # ### end Alembic commands ###
